### ISSUE TITLE
No tests on Travis

### ISSUE THREAD

**Issue by s-zeng** [peterzhu2118/algorithms#1]
Implement CI for the build but without actually running any tests??? At the very least, the tests you do have don't seem to be showing up on Travis Ci

**Comment by peterzhu2118** [comment]
https://github.com/peterzhu2118/algorithms/tree/fail_test

The Travis tests are working, I changed one test to make it fail in this branch and it indeed fails.

**Comment by s-zeng** [comment]
Test results don't seem to be logged in the travis log?

**Comment by peterzhu2118** [comment]
Idk whats up with the logs.

**Comment by peterzhu2118** [comment]
It shows up what failed, and nothing else.

**Comment by s-zeng** [comment]
Okay
